-- ============================================================================
-- MOVED: the schema now lives in supabase/migrations/
-- ============================================================================
-- This file used to be the copy-paste-into-Studio schema. The project now uses
-- Supabase CLI migrations instead:
--
--   supabase/migrations/20260611000000_baseline.sql   ← the schema up to 2026-06-11
--   supabase/migrations/<timestamp>_<name>.sql        ← every change after that
--
-- To change the schema:
--   1. supabase migration new my_change      (creates a timestamped file)
--   2. write the SQL in that file
--   3. supabase db push                      (applies pending migrations)
--      …or just push to main — the GitHub Action runs db push automatically.
--
-- Never edit an already-pushed migration; add a new one.
